
<div class="field linkedin_profile">
   <label class="label" for="linkedin_profile">
       <span><?= $block->escapeHtml(__('LinkedIn Profile')) ?></span>
</label>
<div class="control">
    <input type="text"  id="linkedin_profile" name="linkedin_profile" title="<?= $block->escapeHtmlAttr(__('LinkedIn Profile')) ?>" class="input-text"
      data-validate='{"validate-length maximum-length-250":true, "validate-url": true}'/>
</div>
</div>



